metadata:
  name: whereami
  label: whereami
configurations:
  image: gcr.io/google-samples/whereami:v1.2.19
  port: 8080
autoscaler:
  min: 1
  max: 10
  targetCPU: 50
security:
  tls:
    CertFile: $TLS_CERT
    PrivateKeyFile: $TLS_PRIVATE_KEY_FILE
